// ENB Shared Constants — professions, business categories, business types
// Import from here everywhere to keep lists in sync

export const PROFESSIONS = [
  'Allopathic Doctor',
  'Artist',
  'Baker / Confectioner',
  'Business Owner',
  'Carpenter',
  'Chef / Cook',
  'Cobbler / Shoe Repairer',
  'Community Food Guardian',
  'Community Health Worker',
  'Contractor',
  'Delivery Rider',
  'Developer / IT',
  'Driver (Taxi/Car)',
  'Dry Fruit Merchant',
  'Electrical Shop (Wires, Lights, Fittings)',
  'Electrician',
  'Electronic Appliances Shop',
  'Electronics Technician',
  'Engineer',
  'Farmer',
  'Food Runner',
  'Fruit & Veg Vendor',
  'Homeopathic Doctor',
  'Mechanic / Auto Technician',
  'Milkman / Dairy',
  'Nurse / Midwife',
  'Other',
  'Painter / Mason',
  'Park / Garden Worker',
  'Pharmacist',
  'Plumber',
  'Private Tutor',
  'Religious Scholar',
  'Retired',
  'Rickshaw / Auto Driver',
  'Security Guard / Watchman',
  'Shopkeeper / Retailer',
  'Social Worker',
  'Street Sweeper',
  'Street Vendor',
  'Student',
  'Tailor / Seamstress',
  'Teacher',
  'Volunteer',
  'Waste Collector / Recycler',
  'Welder',
  'Wholesale Trader',
];

// Business categories — used in PartnerManager, PartnerSignup, BusinessDirectory
export const BUSINESS_CATEGORIES = [
  'Allopathic Clinic / Doctor',
  'Auto Garage / Mechanic',
  'Bakery',
  'Barber / Salon',
  'Cobbler / Shoe Repair',
  'Dhaba / Tea Stall',
  'Dry Fruit Merchant',
  'Electrical Shop (Wires, Lights, Fittings)',
  'Electrical Supplies',
  'Electronic Appliances Shop',
  'Fruit & Vegetable Shop',
  'Grocery / General Store',
  'Hardware / Plumbing Supply',
  'Homeopathic Doctor / Shop',
  'Laundry / Dry Cleaner',
  'Pansar (Unani / Herbal)',
  'Pharmacy',
  'Printing / Stationery',
  'Restaurant / Food',
  'School / Academy',
  'Sweet Shop / Mithai',
  'Tailor / Alteration Shop',
  'Tuition Centre',
  'Wholesale Market',
  'Other',
];

// Business types with emoji — for display in directory
export const BUSINESS_TYPE_EMOJI: Record<string, string> = {
  'Dhaba / Tea Stall': '☕',
  'Restaurant / Food': '🍽️',
  'Bakery': '🥖',
  'Sweet Shop / Mithai': '🍬',
  'Grocery / General Store': '🛒',
  'Fruit & Vegetable Shop': '🥕',
  'Wholesale Market': '🏪',
  'Pharmacy': '💊',
  'Allopathic Clinic / Doctor': '🏥',
  'Homeopathic Doctor / Shop': '🌿',
  'Pansar (Unani / Herbal)': '🌱',
  'Auto Garage / Mechanic': '🔧',
  'Electrical Supplies': '⚡',
  'Hardware / Plumbing Supply': '🪛',
  'Printing / Stationery': '🖨️',
  'Tailor / Alteration Shop': '🪡',
  'Cobbler / Shoe Repair': '👞',
  'Barber / Salon': '✂️',
  'Laundry / Dry Cleaner': '👕',
  'School / Academy': '🏫',
  'Tuition Centre': '📚',
  'Electrical Shop (Wires, Lights, Fittings)': '💡',
  'Electronic Appliances Shop': '📱',
  'Dry Fruit Merchant': '🥜',
  'Other': '🏬',
};
